# utils/fetch_assets.py
import requests

def fetch_assets_for_location(location_id) -> list:
    """
    Simulates fetching asset data from an external API for a given location.
    Replace this with actual API calls later using requests.
    """
    # fake_response = {
    #     "assets": [
    #         {
    #             "asset_id": 608,
    #             "asset_name": "Banner Display",
    #             "asset_type_id": 5,
    #             "frequency_id": 2,
    #             "frequency": "day",
    #             "company_id": 288,
    #             "company_name": "Kroot Memorial High School",
    #             "company_type_id": 3,
    #             "rate": "550.00",
    #             "reach": 500,
    #             "asset_guid": "WAW538",
    #             "details": "Showcase your brand at Kroot Memorial School with banner displays in high-traffic areas like entrances, common zones, and sports grounds.",
    #             "quantity": 3,
    #             "icon": "https://exprscdn.univerze.com/univerze/assets/icons/standee.svg",
    #             "background_image": "https://exprscdn.univerze.com/univerze/assets/background_images/standeeSVG.svg",
    #             "locality_id": 136,
    #             "city_id": 232,
    #             "state_id": 21,
    #             "asset_type_name": "Standees",
    #             "locality": "Wanwadi",
    #             "city": "Pune",
    #             "state": "Maharashtra",
    #             "company_type": "Universities / Colleges",
    #             "asset_assignees": None,
    #             "assignees": "Ashish",
    #             "assignees_count": 1,
    #             "slots_per_asset": 30,
    #             "create_time": "2025-04-14T09:09:22.000Z",
    #             "role_name": "assets_owner",
    #             "role_id": 2,
    #             "owner": "Ashish",
    #             "assets": 1,
    #             "auto_approval": 0,
    #             "is_disabled": 0,
    #             "user_location_id": 337,
    #             "available_slots": 90
    #         },
    #         {
    #             "asset_id": 609,
    #             "asset_name": "LED Street Screen",
    #             "asset_type_id": 6,
    #             "frequency_id": 2,
    #             "frequency": "day",
    #             "company_id": 102,
    #             "company_name": "Mumbai City Mall",
    #             "company_type_id": 2,
    #             "rate": "1500.00",
    #             "reach": 2000,
    #             "asset_guid": "LED991",
    #             "details": "High-visibility LED screen near the entrance of Mumbai City Mall. Great for mass outreach.",
    #             "quantity": 1,
    #             "icon": "",
    #             "background_image": "",
    #             "locality_id": 145,
    #             "city_id": 100,
    #             "state_id": 21,
    #             "asset_type_name": "Screens",
    #             "locality": "Kurla",
    #             "city": "Mumbai",
    #             "state": "Maharashtra",
    #             "company_type": "Malls",
    #             "asset_assignees": None,
    #             "assignees": "Ravi",
    #             "assignees_count": 1,
    #             "slots_per_asset": 15,
    #             "create_time": "2025-04-10T08:00:00.000Z",
    #             "role_name": "manager",
    #             "role_id": 3,
    #             "owner": "Ravi",
    #             "assets": 1,
    #             "auto_approval": 1,
    #             "is_disabled": 0,
    #             "user_location_id": 341,
    #             "available_slots": 15
    #         },
    #         {
    #             "asset_id": 610,
    #             "asset_name": "College Fest Stall",
    #             "asset_type_id": 7,
    #             "frequency_id": 3,
    #             "frequency": "week",
    #             "company_id": 215,
    #             "company_name": "Delhi Tech University",
    #             "company_type_id": 1,
    #             "rate": "3000.00",
    #             "reach": 800,
    #             "asset_guid": "STALL777",
    #             "details": "Engage directly with students during the annual fest with a customizable on-ground stall.",
    #             "quantity": 2,
    #             "icon": "",
    #             "background_image": "",
    #             "locality_id": 112,
    #             "city_id": 200,
    #             "state_id": 10,
    #             "asset_type_name": "Stalls",
    #             "locality": "Rohini",
    #             "city": "Delhi",
    #             "state": "Delhi",
    #             "company_type": "Universities",
    #             "asset_assignees": None,
    #             "assignees": "Megha",
    #             "assignees_count": 1,
    #             "slots_per_asset": 10,
    #             "create_time": "2025-04-12T12:00:00.000Z",
    #             "role_name": "event_manager",
    #             "role_id": 4,
    #             "owner": "Megha",
    #             "assets": 1,
    #             "auto_approval": 1,
    #             "is_disabled": 0,
    #             "user_location_id": 320,
    #             "available_slots": 20
    #         },
    #         {
    #             "asset_id": 611,
    #             "asset_name": "Apartment Poster Board",
    #             "asset_type_id": 8,
    #             "frequency_id": 1,
    #             "frequency": "month",
    #             "company_id": 319,
    #             "company_name": "Prestige Apartments",
    #             "company_type_id": 4,
    #             "rate": "400.00",
    #             "reach": 150,
    #             "asset_guid": "APT404",
    #             "details": "Posters in lifts and common areas to build consistent recall in a residential community.",
    #             "quantity": 5,
    #             "icon": "",
    #             "background_image": "",
    #             "locality_id": 129,
    #             "city_id": 301,
    #             "state_id": 22,
    #             "asset_type_name": "Posters",
    #             "locality": "Whitefield",
    #             "city": "Bangalore",
    #             "state": "Karnataka",
    #             "company_type": "Residential Societies",
    #             "asset_assignees": None,
    #             "assignees": "Nina",
    #             "assignees_count": 2,
    #             "slots_per_asset": 25,
    #             "create_time": "2025-04-13T14:30:00.000Z",
    #             "role_name": "resident_manager",
    #             "role_id": 5,
    #             "owner": "Nina",
    #             "assets": 1,
    #             "auto_approval": 1,
    #             "is_disabled": 0,
    #             "user_location_id": 345,
    #             "available_slots": 125
    #         },
    #         {
    #             "asset_id": 612,
    #             "asset_name": "D2D Pamphlet Delivery",
    #             "asset_type_id": 9,
    #             "frequency_id": 3,
    #             "frequency": "week",
    #             "company_id": 400,
    #             "company_name": "Hyderabad Doorway Distributors",
    #             "company_type_id": 6,
    #             "rate": "250.00",
    #             "reach": 300,
    #             "asset_guid": "D2D202",
    #             "details": "Silent sampling via doorstep pamphlet delivery in key Hyderabad residential zones.",
    #             "quantity": 10,
    #             "icon": "",
    #             "background_image": "",
    #             "locality_id": 178,
    #             "city_id": 401,
    #             "state_id": 30,
    #             "asset_type_name": "D2D",
    #             "locality": "Gachibowli",
    #             "city": "Hyderabad",
    #             "state": "Telangana",
    #             "company_type": "Distributors",
    #             "asset_assignees": None,
    #             "assignees": "Shyam",
    #             "assignees_count": 1,
    #             "slots_per_asset": 50,
    #             "create_time": "2025-04-09T11:11:11.000Z",
    #             "role_name": "ops_lead",
    #             "role_id": 6,
    #             "owner": "Shyam",
    #             "assets": 1,
    #             "auto_approval": 1,
    #             "is_disabled": 0,
    #             "user_location_id": 312,
    #             "available_slots": 500
    #         },
    #         {
    #             "asset_id": 613,
    #             "asset_name": "Mall Interactive Booth",
    #             "asset_type_id": 10,
    #             "frequency_id": 2,
    #             "frequency": "day",
    #             "company_id": 500,
    #             "company_name": "Phoenix MarketCity",
    #             "company_type_id": 2,
    #             "rate": "2000.00",
    #             "reach": 1200,
    #             "asset_guid": "INT909",
    #             "details": "Interactive booth near the food court to drive brand engagement through games, contests or samples.",
    #             "quantity": 1,
    #             "icon": "",
    #             "background_image": "",
    #             "locality_id": 150,
    #             "city_id": 232,
    #             "state_id": 21,
    #             "asset_type_name": "Exhibits",
    #             "locality": "Viman Nagar",
    #             "city": "Pune",
    #             "state": "Maharashtra",
    #             "company_type": "Malls",
    #             "asset_assignees": None,
    #             "assignees": "Isha",
    #             "assignees_count": 1,
    #             "slots_per_asset": 5,
    #             "create_time": "2025-04-13T18:00:00.000Z",
    #             "role_name": "marketing_exec",
    #             "role_id": 7,
    #             "owner": "Isha",
    #             "assets": 1,
    #             "auto_approval": 1,
    #             "is_disabled": 0,
    #             "user_location_id": 355,
    #             "available_slots": 5
    #         },
    #         {
    #             "asset_id": 609,
    #             "asset_name": "Digital Signage",
    #             "asset_type_id": 6,
    #             "frequency_id": 1,
    #             "frequency": "hour",
    #             "company_id": 289,
    #             "company_name": "Pune International School",
    #             "company_type_id": 4,
    #             "rate": "750.00",
    #             "reach": 600,
    #             "asset_guid": "WAW539",
    #             "details": "Engage your audience with dynamic digital signage at Pune International School.",
    #             "quantity": 2,
    #             "icon": "https://exprscdn.univerze.com/univerze/assets/icons/digital_signage.svg",
    #             "background_image": "https://exprscdn.univerze.com/univerze/assets/background_images/digital_signage.svg",
    #             "locality_id": 137,
    #             "city_id": 233,
    #             "state_id": 21,
    #             "asset_type_name": "Digital Displays",
    #             "locality": "Kothrud",
    #             "city": "Pune",
    #             "state": "Maharashtra",
    #             "company_type": "Schools",
    #             "asset_assignees": None,
    #             "assignees": "Ravi",
    #             "assignees_count": 1,
    #             "slots_per_asset": 20,
    #             "create_time": "2025-04-15T09:09:22.000Z",
    #             "role_name": "assets_owner",
    #             "role_id": 2,
    #             "owner": "Ravi",
    #             "assets": 1,
    #             "auto_approval": 0,
    #             "is_disabled": 0,
    #             "user_location_id": 338,
    #             "available_slots": 80
    #         },
    #         {
    #             "asset_id": 610,
    #             "asset_name": "Event Booth",
    #             "asset_type_id": 7,
    #             "frequency_id": 3,
    #             "frequency": "week",
    #             "company_id": 290,
    #             "company_name": "Pune Tech Hub",
    #             "company_type_id": 5,
    #             "rate": "1200.00",
    #             "reach": 800,
    #             "asset_guid": "WAW540",
    #             "details": "Showcase your products at the Pune Tech Hub with our event booths.",
    #             "quantity": 1,
    #             "icon": "https://exprscdn.univerze.com/univerze/assets/icons/event_booth.svg",
    #             "background_image": "https://exprscdn.univerze.com/univerze/assets/background_images/event_booth.svg",
    #             "locality_id": 138,
    #             "city_id": 234,
    #             "state_id": 21,
    #             "asset_type_name": "Booths",
    #             "locality": "Hinjewadi",
    #             "city": "Pune",
    #             "state": "Maharashtra",
    #             "company_type": "Tech Companies",
    #             "asset_assignees": None,
    #             "assignees": "Sneha",
    #             "assignees_count": 1,
    #             "slots_per_asset": 15,
    #             "create_time": "2025-04-16T09:09:22.000Z",
    #             "role_name": "assets_owner",
    #             "role_id": 2,
    #             "owner": "Sneha",
    #             "assets": 1,
    #             "auto_approval": 0,
    #             "is_disabled": 0,
    #             "user_location_id": 339,
    #             "available_slots": 70
    #         },
    #     ]
    # }

    url = "https://devapi.monetez.com/api/univerze/v1/assetsforMediaPlanner"
    payload = {
        "id": location_id,
    }

    try:
        response = requests.post(url, json=payload)
        response.raise_for_status()
        data = response.json()

        if not data.get("success") or "data" not in data:
            return []

        assets_info = []

        for asset in data["data"]:
            assets_info.append({
                "asset_name": asset.get("asset_name"),
                "company_name": asset.get("company_name"),
                "rate": asset.get("rate"),
                "frequency": asset.get("frequency"),
                "details": asset.get("details"),
                "reach": asset.get("reach"),
                "asset_type": asset.get("asset_type_name"),
                "quantity" : asset.get("quantity")
                # "available_slots": asset.get("slots_per_asset", 0) * asset.get("quantity", 1),
            })

        return assets_info

    except requests.exceptions.RequestException as e:
        print(f"API request failed: {e}")
        return []



# print(fetch_assets_for_location(228))

# Name
# Rate
# frequency
# Details